import { createTurtleRace } from "./turtle-race.js";
import { createCatchApple } from "./catch-the-apple.js";
import { createCoinCollector } from "./coin-collector.js";
import { createBalloonPop } from "./balloon-pop.js";
import { createSpaceCatcher } from "./space-catcher.js";
import { createCarDodge } from "./car-dodge.js";
import { createDinoJump } from "./dino-jump.js";
import { createMiniPong } from "./mini-pong.js";
import { createMiniSnake } from "./mini-snake.js";
import { createCrossRoad } from "./cross-the-road.js";
import { createSpaceShooter } from "./mini-space-shooter.js";

export const games = [
  { id: "turtle-race", title: "Turtle Race", emoji: "🐢", level: "Beginner", description: "Watch four turtles race with randomized speed every round.", instructions: "Start the game and see which turtle reaches the finish line first. Restart for a new race.", skills: ["movement", "loops", "randomness"], actions: [], create: createTurtleRace },
  { id: "catch-the-apple", title: "Catch the Apple", emoji: "🍎", level: "Beginner", description: "Slide the basket left and right to catch falling apples.", instructions: "Use Left/Right or A/D. Catch apples before they hit the ground. You have three lives.", skills: ["keyboard input", "coordinates", "score", "collision"], actions: [{ id: "left", label: "← Left" }, { id: "right", label: "Right →" }], create: createCatchApple },
  { id: "coin-collector", title: "Coin Collector", emoji: "🪙", level: "Beginner", description: "Move around the board collecting as many coins as possible.", instructions: "Use arrow keys or WASD. Collect as many coins as you can before the 30-second timer ends.", skills: ["2D movement", "timers", "collision", "random positions"], actions: [{ id: "up", label: "↑" }, { id: "left", label: "←" }, { id: "down", label: "↓" }, { id: "right", label: "→" }], create: createCoinCollector },
  { id: "balloon-pop", title: "Balloon Pop", emoji: "🎈", level: "Beginner", description: "Pop moving balloons with the mouse or a finger before time runs out.", instructions: "Click or tap directly on balloons. Each successful pop adds one point.", skills: ["mouse/touch input", "timers", "moving objects"], actions: [], create: createBalloonPop },
  { id: "space-catcher", title: "Space Catcher", emoji: "🚀", level: "Beginner", description: "Pilot a tiny ship and rescue falling stars.", instructions: "Move left and right with the arrows or A/D. Catch stars before they fall off screen.", skills: ["movement", "falling objects", "lives", "speed"], actions: [{ id: "left", label: "← Left" }, { id: "right", label: "Right →" }], create: createSpaceCatcher },
  { id: "car-dodge", title: "Car Dodge", emoji: "🚗", level: "Intermediate", description: "Change lanes and survive increasingly fast traffic.", instructions: "Use Left/Right or A/D to change lanes. Avoid every red car for as long as possible.", skills: ["lanes", "obstacles", "difficulty", "game over"], actions: [{ id: "left", label: "← Left" }, { id: "right", label: "Right →" }], create: createCarDodge },
  { id: "dino-jump", title: "Dino Jump", emoji: "🦖", level: "Intermediate", description: "A tiny endless runner inspired by the classic offline dinosaur game.", instructions: "Press Space, Up, W, or Jump to leap over each cactus. The cactus gets faster.", skills: ["gravity", "velocity", "jumping", "collision"], actions: [{ id: "jump", label: "↑ Jump" }], create: createDinoJump },
  { id: "mini-pong", title: "Mini Pong", emoji: "🏓", level: "Intermediate", description: "Keep the ball in play against a simple computer paddle.", instructions: "Move your left paddle with Up/Down or W/S. First player to score five points wins.", skills: ["bouncing", "velocity", "simple AI", "scoring"], actions: [{ id: "up", label: "↑ Up" }, { id: "down", label: "↓ Down" }], create: createMiniPong },
  { id: "mini-snake", title: "Mini Snake", emoji: "🐍", level: "Intermediate", description: "Grow your snake by eating food without crashing.", instructions: "Use arrows or WASD. Eat the red food and avoid walls and your own tail.", skills: ["game loop", "grid movement", "arrays", "self-collision"], actions: [{ id: "up", label: "↑" }, { id: "left", label: "←" }, { id: "down", label: "↓" }, { id: "right", label: "→" }], create: createMiniSnake },
  { id: "cross-the-road", title: "Cross the Road", emoji: "🐸", level: "Intermediate", description: "Guide the frog across busy traffic lanes and climb levels.", instructions: "Use arrows or WASD to reach the top. Each crossing raises the level and speeds up traffic.", skills: ["hazards", "levels", "lives", "difficulty scaling"], actions: [{ id: "up", label: "↑" }, { id: "left", label: "←" }, { id: "down", label: "↓" }, { id: "right", label: "→" }], create: createCrossRoad },
  { id: "mini-space-shooter", title: "Mini Space Shooter", emoji: "👾", level: "Intermediate", description: "Move, fire, and clear a small alien fleet before it lands.", instructions: "Move with Left/Right or A/D. Fire with Space, Up, or the Fire button. Destroy every alien.", skills: ["projectiles", "enemies", "collision", "win state"], actions: [{ id: "left", label: "← Left" }, { id: "fire", label: "Fire" }, { id: "right", label: "Right →" }], create: createSpaceShooter },
];
